### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by hildjj** [peggyjs/peggy-tag#1]
@sanket143 can you take a look at this please, to see if it's more-or-less what you wanted, and to see if there's anything that can be improved?

**Comment by hildjj** [comment]
@Mingun FYI.  Let me know if you think this is harmful before I release, please.

**Comment by hildjj** [comment]
See https://github.com/peggyjs/code-peggy-language/issues/21 and https://github.com/peggyjs/code-peggy-language/issues/22 for discussion and context.

**Comment by Mingun** [comment]
It seems you should use `options.grammarSource` here instead of `"peggy-tag-parser"`:
https://github.com/peggyjs/peggy-tag/blob/da6744153604aa10418de49801bd03d82b9235f5/lib/index.js#L31-L34

**Comment by hildjj** [comment]
Yes, great catch, thanks.

**Comment by hildjj** [comment]
PR #5 tracking changes we come up with here.
